version: "3"

services:
  mongo:
    image: mongo:3.6
    restart: on-failure
    volumes:
      - mongo-data:/data/db
  node:
    image: node:10-alpine
    restart: on-failure
    volumes:
      - ./src:/usr/src/app/src:ro
      - ./package.json:/usr/src/app/package.json:ro
      - ./package-lock.json:/usr/src/app/package-lock.json
      - node_modules:/usr/src/app/node_modules
    working_dir: /usr/src/app
    environment:
      NODE_ENV: production
    ports:
      - "80:80"
    command: sh -c 'npm install && node src/index.js'

volumes:
  mongo-data: {}
  node_modules: {}